from locust import HttpUser, task, between, events
import os

# Configure via environment variables
TEST_USER_EMAIL = os.getenv("LOCUST_TEST_EMAIL", "test_locust@example.com")
TEST_USER_PASSWORD = os.getenv("LOCUST_TEST_PASSWORD", "testpass123")

class APISimUser(HttpUser):
    wait_time = between(1, 3)

    def on_start(self):
        # Try to login and store auth token
        resp = self.client.post("/auth/login", json={"email": TEST_USER_EMAIL, "password": TEST_USER_PASSWORD})
        if resp.status_code == 200:
            self.token = resp.json().get("access_token")
        else:
            self.token = None

    @task(5)
    def health(self):
        self.client.get("/health")

    @task(3)
    def root(self):
        self.client.get("/")

    @task(10)
    def list_expenses(self):
        headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        self.client.get("/expenses/", headers=headers)

    @task(2)
    def create_expense(self):
        headers = {"Authorization": f"Bearer {self.token}"} if self.token else {}
        payload = {
            "title": "Locust expense",
            "amount": 1000,
            "category": "Locust",
            "description": "generated by locust",
            "date": "2025-11-20T00:00:00Z",
            "type": "expense",
            "is_recurring": False
        }
        self.client.post("/expenses/", json=payload, headers=headers)

# Optional: event hooks to print summary
@events.quitting.add_listener
def _(environment, **kw):
    print("Locust test finished")
